# Generated by Django 4.2.6 on 2023-12-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_customuser_date_of_birth_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='api_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
