# Generated by Django 4.2.6 on 2023-11-19 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_recipe_cooking_time_recipe_preparation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_time',
        ),
    ]
