# Generated by Django 4.2.6 on 2023-11-19 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_recipe_cooking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_time',
        ),
    ]
